# Generated by Django 5.2.5 on 2025-10-27 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('precio_arriendo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disponible', models.BooleanField(default=True)),
                ('calificacion', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='peliculas/')),
            ],
        ),
    ]
