# Generated by Django 5.2.5 on 2025-11-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='precio_arriendo',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
