# Generated by Django 4.1.13 on 2025-11-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_pelicula_descripcion_alter_pelicula_precio_arriendo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='precio_compra',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='precio_arriendo',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7),
        ),
    ]
