# Generated by Django 4.1.13 on 2025-11-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0003_pelicula_precio_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='peliculas_videos/'),
        ),
    ]
