# Generated by Django 4.1.13 on 2025-11-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0004_pelicula_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
