# Generated by Django 4.1.13 on 2025-12-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0005_pelicula_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(choices=[('Acción', 'Acción'), ('Terror', 'Terror'), ('Romance', 'Romance'), ('Comedia', 'Comedia'), ('Infantil', 'Infantil')], max_length=50),
        ),
    ]
