# Generated by Django 5.2.5 on 2025-11-10 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0001_initial'),
        ('peliculas', '0002_pelicula_descripcion_alter_pelicula_precio_arriendo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('arriendo', 'Arriendo'), ('compra', 'Compra')], max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('completada', 'Completada'), ('devuelta', 'Devuelta')], default='completada', max_length=10)),
                ('motivo_devolucion', models.TextField(blank=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('devuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones', to=settings.AUTH_USER_MODEL)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='peliculas.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.DeleteModel(
            name='Arriendo',
        ),
    ]
