# Generated by Django 4.1.13 on 2025-11-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0002_transaccion_delete_arriendo'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='mp_preference_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='mp_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('devuelta', 'Devuelta'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10),
        ),
    ]
