# Generated by Django 4.1.13 on 2025-11-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0003_transaccion_mp_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='fecha_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='link_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
