# Generated by Django 4.1.13 on 2025-11-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0004_transaccion_fecha_expira_transaccion_link_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccion',
            old_name='fecha_expira',
            new_name='ver_expires_at',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='link_token',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='ver_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
